export default [
  { name: 'The Star', hostname: 'www.thestar.com.my' },
  { name: 'Malay Mail', hostname: 'www.malaymail.com' },
  { name: 'PH Manifesto GE14', hostname: 'pakatanharapan.com.my' },
  { name: 'MalaysiaKini', hostname: 'www.malaysiakini.com' },
  { name: 'The Malaysian Insight', hostname: 'www.themalaysianinsight.com' },
  { name: 'New Straits Times', hostname: 'www.nst.com.my' },
  { name: 'The Sun', hostname: 'www.thesundaily.my' },
  { name: 'Utusan Borneo', hostname: 'www.utusanborneo.com.my' },
  { name: 'The Borneo Post', hostname: 'www.theborneopost.com' },
  { name: 'Daily Express', hostname: 'www.dailyexpress.com.my' },
  { name: 'Free Malaysia Today', hostname: 'www.freemalaysiatoday.com' },
  { name: 'Official Facebook', hostname: 'www.facebook.com' },
  { name: 'Official Twitter', hostname: 'www.twitter.com' },
  { name: 'PH Manifesto', hostname: 'kempen.s3.amazonaws.com' },
  { name: 'Bernama', hostname: 'www.bernama.com'},
  { name: 'The Straits Times', hostname: 'www.straitstimes.com'},
  { name: 'The Edge Markets', hostname: 'www.theedgemarkets.com' },
  { name: 'Utusan', hostname: 'www.utusan.com.my'},
  { name: 'Berita Harian', hostname: 'www.bharian.com.my'}
]
